### PR TITLE
Highlight current user

### PR DESCRIPTION
**Pull request by bschmeck**
We have to push the authenticated user through a couple of layers to enable highlighting, but that makes not highlighting the user's feed easy (we just don't push it through.)

Also added User.equals, but someone with more Java knowledge than I should double check it.

### CODE REVIEW

**Comment by bschmeck** [comment]
Right now it draws a border around the love.  I like the idea of a vertical line on the left side, but haven't been able to figure that out.  Will keep working on it.

**Comment by bschmeck** [comment]
Working on the merge conflict

**Comment by bschmeck** [comment]
Ok, this was broken on the user page, but everything is working now.  Colors aren't great.

**Comment by AnthonyCaliendo** [comment]
@bschmeck While doing the other assignments, I ran into [drawableLeft](http://developer.android.com/reference/android/widget/TextView.html#attr_android:drawableLeft).  It allows you to set a drawable on one side of `TextView`.

You may be able to do this on the reason and message, but it won't be over the entire view, unfortunately.

**Pull request merged**
